console_utils.invalid_enter_again=Invalid value. Please enter again:
console_utils.invalid_enter_again_varname=Invalid value. Please enter ${0} again:
console_utils.confirm_value=Confirm ${0}:
console_utils.unmatched_values=The ${0} and Confirm ${0} do not match.
